# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('subcategoria', models.CharField(max_length=20)),
                ('unidade', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ingrediente',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('subcategoria', models.CharField(max_length=20)),
                ('unidade', models.CharField(max_length=10)),
                ('estoque', models.FloatField()),
                ('ultima_compra', models.DateField()),
                ('prazo_compra', models.IntegerField()),
                ('total_comprado', models.FloatField()),
                ('valor_comprado', models.FloatField()),
                ('preco_medio', models.FloatField()),
            ],
            options={
                'db_table': 'materiais',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='Quantidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_receita', models.FloatField()),
                ('quantidade_unitaria', models.FloatField()),
                ('rendimento', models.FloatField()),
                ('obs', models.CharField(max_length=30)),
                ('ingrediente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Ingrediente')),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Produto')),
            ],
            options={
                'db_table': 'quantidade',
            },
        ),
    ]
