# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170526_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producao',
            old_name='produto_id',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='quantidade',
            old_name='ingrediente_id',
            new_name='ingrediente',
        ),
        migrations.RenameField(
            model_name='quantidade',
            old_name='produto_id',
            new_name='produto',
        ),
    ]
